### ISSUE TITLE
REGARDING DGPU

### ISSUE THREAD

**Issue by sai5567** [AswindevSP/Dell-Inspiron-5567-BigSur#3]
Hey bro did u have a kext which disables unused dgpu in your efi or do u know a way to disable dgpu as it consumes a lot of power from battery

**Comment by AswindevSP** [comment]
Just add -wegnoegpu in boot args. Its the easiest methord.

**Comment by AswindevSP** [comment]
Disabled eGPU from device properties, increased vram to 2048 also removed the alcid from boot args and directly patched to device properties.
