### ISSUE TITLE
REGARDING INSTALLATION OF BIG SUR

### ISSUE THREAD

**Issue by sai5567** [AswindevSP/Dell-Inspiron-5567-BigSur#4]
Hi bro 
previously i was on catalina 10.15.5 and used open core 0.6.0 today saw your efi and i tried to install bigsur but after first phase of installation the system keeps rebooting and i dont know why
can u tell me what procedure u used to install bigsur

**Comment by sai5567** [comment]
Bro i tried to install bigsur as mentioned in dortana and using ur EFI but what's happening is at first i didnt see the external usb of big sur on oc bootloader so i rechecked everything and then also i wasnt able to see the external usb of big sur
So what i did was i booted to recovery using my efi which is used for catalina and i installed big sur but problem is after installation my laptop rebooted normally but this time after reaching apple logo it reboots again and this loop continues 
DO U HAVE ANY SOLUTIONS FOR THESE THINGS

**Comment by AswindevSP** [comment]
Use the PreInstall EFI folder in the repository for the initial installation of big sur. After the setup is complete you can use the other EFI. 

PreInstall EFI only contains 2 dsdt files. And limited kext. 

After installation make sure you generate your own serial number and other stuff from OC configurator.

**Comment by sai5567** [comment]
Thnx for the help bro 
Yesterday i spend almost 6hrs for finding whats happening and why cant i be able to install big sur so finally i gave up and continued to use catalina
Today after seeing your reply i did what u said and i was  able to install big sur 
Thnx again also i saw airportitlwm.kext and put in the config.plist and now i can use wifi without the help of heliport if interested u can also try it too

**Comment by sai5567** [comment]
Bro when i put my laptop to sleep and wake it up then password coloum is pressed by random numbers and it wont stop until i restarted the laptop
Is there anything i need to do for issues like these

**Comment by AswindevSP** [comment]
I don't know how to fix it but there are two ways to get around it. 
1. Wait a few seconds for it to load then type the pass 
2  Turn of Require password after sleep.

**Comment by sai5567** [comment]
Bro when i tried to use ur big sur EFI on catalina and mojave too it says this version of mac os x is not supported 
Why is this happening bro what EFI u used for catalina??

**Comment by AswindevSP** [comment]
-no_compat_check
Add this to the boot args 
It might be a problem with smbios.

**Comment by sai5567** [comment]
Bro thnx alot it worked like charm
Also the sleep/wake issues are due to airportitlwm.kext which i included

**Comment by sai5567** [comment]
hi bro one thing to ask 
how did u install that jack fix in big sur bro
im getting errors
first i cant copy hda verb to /usr/bin it says read only even when i tried to disable SIP
i typed csrutil status and i see something new which says

System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

i searched on google but cant get a way to find the solution so im asking you 
how u managed to do this

**Comment by AswindevSP** [comment]
I was also unable to disable SIP in big sur beta 10. But the headphone jack is working fine. 
https://github.com/hackintosh-stuff/ComboJack      Install this.
Also Alcid = 13 or 21

**Comment by sai5567** [comment]
> I was also unable to mount system as writable in big sur beta 10. But the headphone jack is working fine.
> https://github.com/hackintosh-stuff/ComboJack Install this.
> Also Alcid = 13 or 21
> 
> To mount system as writable this might work:
> https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#writing-to-the-macos-system-partition
> But wont get update or it may cause problems during updates.
> Clean installation would be needed next time.

thnx buddy its working like a charm 
before seeing your reply i was preparing for that snapshot thing which i saw on youtube to write to bigsur volumes for this jackfix  but thnx to you it was fixed without doing all that stuff
tnnx again for replying without delay

**Comment by sai5567** [comment]
bro a silly question to ask 
how do u manage to see how much internet data your laptop is using??
when i used bandwidth+ app it doesnt show the inward data it only shows the outgoing data
i see this problem persists on catalina too but in mojave it works fine 
do u know something about this and sry for bothering u and i only ask u as my last hope thnx

**Comment by AswindevSP** [comment]
Try this 
https://www.teamos-hkrg.com/threads/cleanmymac-x-4-6-2-macos%EF%A3%BFapps-%EF%A3%BF%EF%A3%BFteamos%EF%A3%BF%EF%A3%BF.124352/

**Comment by sai5567** [comment]
thnx bro i tried but the results are same may be its the bug in mac os

**Comment by sai5567** [comment]
Bro thnx for helping me in hackintoshing 
one small request whenever u update opencore version please put in ur github repo also whenever i found amazing app or something i will write it here
       Thnx for helping me througout this journey

**Comment by AswindevSP** [comment]
Yeah, I would update the OC whenever a stable version is released. But I won't be updating big sur version until a stable version is released. I don't know maybe I will downgrade to Catallina somday. 
Beta versions are just lot of work and not worth it!
Btw thx for taging along this hackistoh journey. Happy to see that what I am an doing here is helping someone out there. 🙃
