### ISSUE TITLE
REGARDING NEW OC VERSION

### ISSUE THREAD

**Issue by sai5567** [AswindevSP/Dell-Inspiron-5567-BigSur#5]
Bro i tried your efi on mojave as i rolled.back to mojave from bigsur but when i tried to set secureboot to default there will be no boot options present only blank screen appears on opencore bootloader i also tried no compact check but no use 
I need secureboot to be default because airportitlwm kext only works when secureboot is default 
Do u have any solution for this??

**Comment by sai5567** [comment]
The exact issue is when selecting mac os from bootloader the screen goes blank and comes to the same boot options and this cycle goes on

**Comment by sai5567** [comment]
Phew After spending 4hrs of my time finally able to resolve the issue bro
Few key points:
In order to work with secureboot as default we need a fresh install of mac os with that EFI or in my case i selected the same disk which i had mojave installed without clearing the data as the boot disk 
Also in ur EFI i assume few things
Scan policy should be set to 0 but in ur EFI it was set to some other number so i think this is the reason we cant see the bootable external disk directly
And reset nvram was set to false i assume this was to reduce the no of boot entries in the bootloader
So no regrets for spending that time on trail and error
Thnx for the EFI

**Comment by AswindevSP** [comment]
Why mojave isnt it too old?

**Comment by sai5567** [comment]
Yeah its old but somehow i love it

**Comment by sai5567** [comment]
Also as i said the download speed is recorded only in mojave catalina and big sur are not working for me

**Comment by sai5567** [comment]
Hi today tried to update my opencore from 0.6.3 to 0.6.6 and im able to boot successfully but in boot entries there are more than 10 entries showing up like cleannvram.efi,chip tune.efi like that all efis are showing up do u know about these and how to hide them
